Update rust docker image to 1.74
Compiling with Docker is failing on 1.69 due to dependencies requiring a newer Rust version:

```
error: package `clap_lex v0.5.1` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0
Either upgrade to rustc 1.70.0 or newer, or use
cargo update -p clap_lex@0.5.1 --precise ver
where `ver` is the latest version of `clap_lex` supporting rustc 1.69.0
```

With this change it's possible to compile RustHound on Docker again, this was tested with `sudo docker run --rm -v `pwd`:/usr/src/rusthound rusthound windows`